# Generated by Django 3.2.16 on 2023-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
